import os
import torch
import odak
from torchvision import transforms
from torch.utils.data import Dataset


class hologram_dataset(Dataset):
    """
    A class to load hologram datasets generated by Kavaklı et al. "Realistic Defocus Blur for Multiplane Computer-Generated Holography".
    """
    def __init__(self, directory = './dataset/train', key = '*.pt', device = torch.device('cpu')):
        self.filenames = odak.tools.list_files(directory, key = key)
        self.device = device

        
    def __getitem__(self, index):
        self.filename = self.filenames[index]
        data = odak.learn.tools.torch_load(self.filename)
        image = data["target"][1].unsqueeze(0).to(self.device)
        hologram = data["hologram phases"][1].unsqueeze(0).to(self.device)
        image = (image - 0.5) * 2
        hologram = hologram % (2. * odak.pi) / (2. * odak.pi)
        return image, hologram


    def __len__(self):
        return len(self.filenames)
